### PR TITLE
Add main header and container templates

### PR DESCRIPTION
**Pull request by catageek**

### CODE REVIEW

**Comment by adam4813** [comment]
Not sure what Trillek.h gives us that is "main" but looks like it is close to the coding style.

Make sure that indentation is 4 spaces and make sure braces are 1tbc stoutsttup (misspelled?).

These just give us thread safe stl container access?

**Comment by ghost** [comment]
Isn't this specific to networking?

The brace style we're using is from Bjarne Stroustrup's C++ book.

And 4-space indentation.

**Comment by catageek** [comment]
AtomicQueue and AtomicMap are thread-safe containers that will be useful except if Trillek is single threaded...

I removed network specific lines and fix formatting of the main header.

**Comment by Zardoz89** [comment]
> Make sure that indentation is 4 spaces and make sure braces are 1tbc stoutsttup (misspelled?).
> 
> The brace style we're using is from Bjarne Stroustrup's C++ book.

 [Stroustrup style](http://en.wikipedia.org/wiki/Indent_style#Variant:_Stroustrup)

**Comment by adam4813** [comment]
You still forgot to adjust indentation :)

**Comment by catageek** [comment]
Fixed. I hope this is OK now.

**Comment by catageek** [comment]
Forget the last commit and comment. I need to reconfigure Code::Blocks project setting to put spaces and not tabs.

Also, I should not commit before my 2 morning coffees to avoid persisting in my error.

**Comment by Zardoz89** [comment]
Put this file in your root dir of the proyect, and install editorconfig plugin for Code::Blocks : https://github.com/trillek-team/trillek-vcomputer-module/blob/master/.editorconfig

This will auto-setup your IDE to use 4 indent spaces, remove trailing spaces and unix end of line; with this project.

**Comment by tanderegg** [comment]
I think its smart to plan for concurrency from the beginning, unfortunately
its a topic I don't know a whole lot about, so I'll defer to catageek in
this area.  This will be especially import for the server side application,
which will definitely have to make extensive use of concurrency, but is
important for the client too if we want to take advantage of multicore cpus.

**Comment by catageek** [comment]
Fixed !

**Comment by DeVaukz** [comment]
Any reason for using a mutex instead of a lighter weight locking primitive such as a spin lock?

**Comment by catageek** [comment]
No, these considerations have not be taken in account. I am aware that there are some possible improvements.

But I use a threadpool (coming soon...) that limits the number of running threads to a fixed number that can be the number of cores. This means that a blocked thread will rarely cause a context switch and will just wait.

**Comment by adam4813** [comment]
Looking good!

**Comment by catageek** [comment]
Pass on Linux using GCC 4.8.2.

**Comment by adam4813** [comment]
Visual studio doesn't understand varuadic templates yet sadly.

**Comment by catageek** [comment]
Apparently VS supports variadic templates, and make_unique is already implemented: http://msdn.microsoft.com/fr-fr/library/dn439780.aspx

I guess this is why my implementation triggers an error in VS. it should be defined only if not yet implemented.

**Comment by catageek** [comment]
And apparently GCC 4.8.2 has make_unique() also. VS and GCC have same level of functionnality. I wonder why I could compile the PR while you had an error, I should have the error also.

**Comment by ghost** [comment]
Wouldn't `-pedantic` disable that?

**Comment by adam4813** [comment]
It is because I have visual studio 2012. It was never an error about
make_unique but about the variadic template (the ... bit).

Visual studio 2013 has variadic templates though.

**Pull request merged**
