### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Mudman2999**

### CODE REVIEW

**Comment by adam4813** [comment]
Ummm... What does this PR do?

**Comment by adam4813** [comment]
Ohhh!! It's named with a capital D in the branch name hence why it thinks it's different.

**Comment by Meisaka** [comment]
This appears to be a merge from develop to master, the D has nothing to do with that.

**Comment by catageek** [comment]
The merge should be develop -> release-xxx -> master (with tag)

Anyway I don't see the purpose of a merge. Is the develop branch ready for a release ?

**Comment by adam4813** [comment]
No it isn't ready yet i'd say.

**Pull request closed without merging**
