### PR TITLE
Fixing Linux building

### PR DESCRIPTION
**Pull request by Zardoz89**
Linux building was faling becase not was a -lpthread on the link

### CODE REVIEW

**Comment by Zardoz89** [comment]
Sorry for the junk commits. Git really did something very mess here .. I would try to remove some of these commits

edit: I can't remove these annoying merge commits

**Comment by Zardoz89** [comment]
I think that I could clena hte mess doing a new branch and doing cherry pick . I would try it this  Sunday

**Comment by adam4813** [comment]
Squash maybe?

**Comment by Zardoz89** [comment]
> Squash maybe?

I try it, but the "merge" commits aren't listed

**Comment by Zardoz89** [comment]
Ok, I cleaned all the mess and I add a few extras. 
- Less spam on IRC (Travis spam only on failure or when the status changes from failure to success)
- README/ GitHub repo main page now shows Travis status

**Pull request merged**
