### PR TITLE
Generate 3 binaries for server, client and standalone

### PR DESCRIPTION
**Pull request by catageek**
Also try to modularize CMakeList.txt to keep it readable.

Note that maintaining a separate folder for tests makes that we must duplicate modules, or create a hard link in the cmake script. I chose to duplicate the modules.

### CODE REVIEW

**Comment by adam4813** [comment]
I would think that the client could connect to the server or remain standalone. I am uncertain why we would need 2 separate binaries for this purpose.

**Comment by ghost** [comment]
Do we have it decided whether we're going to implement standalone singleplayer or execute a local server process?

**Comment by catageek** [comment]
I removed the standalone binary.

How we will implement standalone mode is not very important at this point, the 2 solutions are easy to implement. I propose to start with a local server and see later what we can simplify in the pipeline.

**Comment by adam4813** [comment]
Can't we make some seamless jump online type game play?

Such as you click connect on a friends server. It will transition you into
their server via wormhole or something in game.

**Comment by Meisaka** [comment]
What I want to know is: how or does this relate to the trillek-server-core repo, is that not where the code should go for the server? (in which case the server-core should probably be a sub-module of the client)

**Comment by adam4813** [comment]
Hmm very good point. Maybe it would be better to keep them separate
concepts that communicate. This would allow modders to more easily modify
just the server, assuming they don't change the protocol.

**Comment by catageek** [comment]
The network layer is common to client and server and the creation of a new packet handler is a specialization of a template with <CLIENT> or <SERVER> parameter.

It means that modders won't be able to create new packet handlers since it is not dynamically loaded. I think this is what you call "changing the protocol".

I am not sure of the purpose or the server repo for the moment, but I think that the current repo could be renamed simply 'core'.

EDIT: In fact modders can implement their own packet handlers, but the class they will override does not exist yet because it will be part of the API (with a hook in the core). The 'server' repo could be renamed 'API' to host the code dedicated to modders.

**Comment by catageek** [comment]
Can you merge this please ? Thanks !

**Comment by adam4813** [comment]
What exactly is this going to do...just make a server binary and client binary now correct?

**Comment by catageek** [comment]
Correct.

**Comment by catageek** [comment]
PR pull in adam4813 develop branch

**Pull request closed without merging**
